version: "3"

services:

  # ===========================
  # |   Uptime Gitlab         |
  # ===========================
  gitlab:
    # ---- Build instructions ----
    container_name: gitlab
    image: gitlab/gitlab-ce:latest

    # ---- Container information ----
    restart: unless-stopped
    hostname: 'gitlab.alexis-vannot.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.alexis-vannot.com'
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab-router.rule=Host(`gitlab.alexis-vannot.com`)
      - traefik.http.routers.gitlab-router.entrypoints=websecure
      - traefik.http.routers.gitlab-router.tls=true
      - traefik.http.routers.gitlab-router.tls.certresolver=letsencrypt
      - traefik.http.services.gitlab-service.loadbalancer.server.port=443
    volumes:
      # Container configuration
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Gitlab data
      - ./gitlab_config:/etc/gitlab
      - ./gitlab_logs:/var/log/gitlab
      - ./gitlab_data:/var/opt/gitlab
    networks:
      - webgateway-traefik

networks:
  webgateway-traefik:
    external: true
