version: "3"

services:

  # ===================
  # |   Gitea         |
  # ===================
  gitea:
    # ---- Build instructions ----
    container_name: gitea
    image: gitea/gitea:nightly

    # ---- Container information ----
    restart: unless-stopped
    depends_on:
      - postgresql-gitea
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgresql-gitea

      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=oH5c4U!JyX3wkVh6@EWu9q4YuMy8fc
    labels:
      - traefik.enable=true
      - traefik.docker.network=webgateway-traefik

      - traefik.http.routers.gitea-http-router.rule=Host(`gitea.alexis-vannot.dev`)
      - traefik.http.routers.gitea-http-router.entrypoints=websecure
      - traefik.http.routers.gitea-http-router.tls=true
      - traefik.http.routers.gitea-http-router.tls.certresolver=letsencrypt
      - traefik.http.routers.gitea-http-router.service=gitea-http-service
      - traefik.http.services.gitea-http-service.loadbalancer.server.port=3000

      - traefik.tcp.routers.gitea-tcp-router.rule=HostSNI(`gitlab.alexis-vannot.dev`)
      - traefik.tcp.routers.gitea-tcp-router.entrypoints=gitea-ssh
      - traefik.tcp.routers.gitea-tcp-router.tls=true
      - traefik.tcp.routers.gitea-tcp-router.tls.certresolver=letsencrypt
      - traefik.tcp.routers.gitea-tcp-router.service=gitea-tcp-service
      - traefik.tcp.services.gitea-tcp-service.loadbalancer.server.port=2222
    volumes:
      # Container configuration
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Gitea data
      - ./gitea_data:/var/lib/gitea
      # Gitea conf
      - ./gitea_conf:/etc/gitea
    networks:
      - webgateway-gitea
      - webgateway-traefik

  # ============================
  # |    PostgreSQL            |
  # ============================
  postgresql-gitea:
    # ---- Build instructions ----
    container_name: postgresql-gitea
    image: postgres:14
    shm_size: 256m

    # ---- Container information ----
    tty: true
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_root_password
    volumes:
      # Container configuration
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # PostgreSQL data
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - webgateway-gitea
    secrets:
      - postgresql_root_password

# ========================
# |  Networks            |
# ========================
networks:
  webgateway-gitea:
    name: webgateway-gitea

  webgateway-traefik:
    external: true

# ========================
# |  Secrets             |
# ========================
secrets:
  postgresql_root_password:
    file: ./.secrets/postgresql_root_password.txt
